core/urls.py
from django.conf.urls import url
from core.feeds import LastPostsFeed
from core.views import PostListView, PostDetailView, PostEditView, PostCreateView, CategoryCreateView, AuthorDetailView, AuthorUpdateView, CategoryListPostsView, rating_up, rating_down, search
from core.forms import CaptchaRegistrationForm
from core.sitemap import PostSitemap
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required
from django.contrib.sitemaps.views import sitemap
from registration.backends.default.views import ActivationView
from registration.backends.default.views import RegistrationView

sitemaps = {
    'fun': PostSitemap,
}

urlpatterns = [
                       # url(r'^$', cache_page(60 * 15)(PostListView.as_view()), name='index'),
                       url(r'^$', PostListView.as_view(), name='index'),
                       url(r'^post/add/$', login_required(PostCreateView.as_view()), name='add_post'),
                       url(r'^category/add/$', login_required(CategoryCreateView.as_view()), name='add_category'),
                       url(r'^category/(?P<name>[-_\w]+)/$', CategoryListPostsView.as_view(), name='list_category'),
                       # url(r'^post/(?P<pk>\d+)/(?P<slug>[-_\w]+)/$', cache_page(60 * 15)(PostDetailView.as_view()), name='post'),
                       url(r'^post/(?P<pk>\d+)/(?P<slug>[-_\w]+)/$', PostDetailView.as_view(), name='post'),
                       url(r'^post/edit/(?P<pk>\d+)/$', login_required(PostEditView.as_view()), name='edit_post'),
                       url(r'^feed/', LastPostsFeed(), name='feed'),
                       url(r'^profile/(?P<pk>\d+)/$', login_required(AuthorDetailView.as_view()), name='profile'),
                       url(r'^profile/(?P<pk>\d+)/edit/$', login_required(AuthorUpdateView.as_view()), name='edit_profile'),
                       url(r'^activate/complete/$', TemplateView.as_view(template_name='registration/activation_complete.html'), name='registration_activation_complete'),
                       url(r'^activate/(?P<activation_key>\w+)/$', ActivationView.as_view(), name='registration_activate'),
                       url(r'^register/$', RegistrationView.as_view(form_class=CaptchaRegistrationForm), name='registration_register'),
                       url(r'^register/complete/$', TemplateView.as_view(template_name='registration/registration_complete.html'), name='registration_complete'),
                       url(r'^rating/(?P<id>\d+)/(?P<slug>[-_\w]+)/up/$', rating_up, name='rating_up'),
                       url(r'^rating/(?P<id>\d+)/(?P<slug>[-_\w]+)/down/$', rating_down, name='rating_down'),
                       url(r'^search_results/', search, name='search'),
                       url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}),
]

core/models.py
from django.db import models
from django.db.models import Q
from django.db.models.signals import post_save
from django.core.mail import send_mail
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.template.defaultfilters import slugify
from django.template import Context
from django.utils.translation import ugettext_lazy as _
from django.utils.http import urlquote
from django.utils import timezone
from unidecode import unidecode
from django.contrib.sitemaps import ping_google
from django.core.cache import cache
from django.conf import settings
from core.utils import read_template, get_random_string
from core.signals import post_save_user
import hmac
import hashlib

from core.utils import send_gearman_mail, get_file_path, send_gearman_jabber

import logging
logger = logging.getLogger(__name__)

RECEIVE_TYPE = (
    (0, _('No updates')),
    (1, _('Mail per post')),
    (2, _('Digest')),
    (3, _('Jabber')),
)


class AuthorUserManager(BaseUserManager):

    def create_user(self, username, email, password, **extra_fields):
        if not email:
            msg = _('Users must have valid email address')
            raise ValueError(msg)

        if not self.check_blacklisted_domain(email):
            msg = _('Registration with this email is not allowed')
            raise ValueError(msg)

        if password is None:
            msg = _('Please supply password')
            raise ValueError(msg)

        if username is None:
            msg = _('Please supply username')

        now = timezone.now()
        user = self.model(email=AuthorUserManager.normalize_email(email),
                          username=username,
                          is_staff=False, is_active=False, is_superuser=False,
                          last_login=now, date_joined=now, **extra_fields)
        user.set_password(password)
        secret = bytes(user.email, 'utf-8')
        data = bytes(user.username, 'utf-8')
        digest = hmac.new(secret, data, digestmod=hashlib.sha256)
        user.registration_hash = digest.hexdigest()
        user.save(using=self._db)

        return user

    def check_blacklisted_domain(self, email):
        domain = email.split("@")[1]
        logger.debug(domain)
        blacklisted_domains = cache.get('blacklisted_domains')
        logger.debug(blacklisted_domains)

        if blacklisted_domains is None and settings.BL_DOMAINS:
            with open(settings.BL_DOMAINS) as f:
                blacklisted_domains = f.read().splitlines()
            cache.set('blacklisted_domains', blacklisted_domains)
            logger.debug(blacklisted_domains)

        if domain in blacklisted_domains:
            logger.info("Registration with blacklisted domain detected")
            return False

        return True

    def create_superuser(self, username, email, password):
        user = self.create_user(username, email, password)
        user.is_active = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class Author(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    username = models.CharField(_('Username'), max_length=50, unique=True)
    first_name = models.CharField(_('First Name'), max_length=150)
    last_name = models.CharField(_('Last Name'), max_length=150)
    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    receive_update = models.PositiveSmallIntegerField(default=1, choices=RECEIVE_TYPE)
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    registration_hash = models.CharField(max_length=64, blank=True)
    avatar = models.ImageField(upload_to=get_file_path, default='avatars/no-img.png', null=True, blank=True)
    jabber_contact = models.CharField(max_length=512, unique=True, null=True, blank=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = AuthorUserManager()

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_short_name(self):
        return "%s" % self.first_name

    def get_fullast_name(self):
        return "%s %s" % (self.first_name, self.last_name)

    def get_username(self):
        return "%s" % self.email

    def get_absolute_url(self):
        return "/profile/%s/" % urlquote(self.pk)

    def email_user(self, subject, message, from_email=None):
        send_mail(subject, message, from_email, [self.email])

    def activate_user(self, user, hash):
        if self.username == user:
            secret = bytes(self.email).encode('utf-8')
            data = bytes(self.username).encode('utf-8')
            computed_hash = hmac.new(secret, data, digestmod=hashlib.sha256).hexdigest()
            if self.registration_hash == hash and self.registration_hash == computed_hash:
                self.is_active = True
                self.save()
                return True
            else:
                return False

    def save(self, *args, **kwargs):
        if self.last_login is None:
            self.last_login = timezone.now()
        if self.username is None or self.username == '':
            self.username = get_random_string(16)
        super(Author, self).save(*args, **kwargs)

    def __str__(self):
        return "%s %s" % (self.first_name, self.last_name)

    def __unicode__(self):
        return "%s %s" % (self.first_name, self.last_name)


class Tag(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(_('name'), max_length=50, db_index=True)

    def __str__(self):
        return "%s" % self.name

    def __unicode__(self):
        return "%s" % self.name


class Category(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(_('name'), max_length=100, unique=True)

    class Meta:
        verbose_name = _('category')
        verbose_name_plural = _('categories')

    def __str__(self):
        return "%s" % self.name

    def __unicode__(self):
        return "%s" % self.name


class Post(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=150)
    content = models.TextField()
    category = models.ForeignKey(Category)
    author = models.ForeignKey(Author)
    date_created = models.DateTimeField(default=timezone.now, db_index=True)
    last_update = models.DateTimeField(default=timezone.now)
    tag = models.ManyToManyField(Tag, related_name="tag_name")
    keywords = models.CharField(max_length=200)
    slug = models.SlugField(max_length=255, blank=True)
    unsafe = models.BooleanField(default=False)

    class Meta:
        verbose_name = _('post')
        verbose_name_plural = _('posts')
        ordering = ['-date_created']

    def save(self, *args, **kwargs):
        created = False
        if self.pk is None:
            created = True

        if self.slug == '':
            self.slug = slugify(unidecode(self.title[:255]))

        super(Post, self).save(*args, **kwargs)

        if not settings.DEBUG:
            try:
                ping_google(sitemap_url='/sitemap.xml')
            except Exception():
                pass

        if created:
            context = {
                "title": self.title,
                "url": "http://fun.mitaka-g.net/post/" + str(self.pk) + "/" + self.slug + "/",
                "content": self.content,
                "author": self.author
            }

            for author in Author.objects.filter(~Q(pk=self.author.pk) & Q(is_active=True)):
                if author.receive_update == 1:
                    logger.info("Sending notification via email to %s", author.email)
                    template = read_template('/home/django/projects/fun/core/templates/core/post_email.txt')
                    send_gearman_mail('New post on fun.mitaka-g.net', template.render(Context(context)), 'webmaster@fun.mitaka-g.net', [author.email], fail_silently=False, auth_user=settings.MANDRILL_USER, auth_password=settings.MANDRILL_API_KEY, host=settings.MANDRILL_HOST)
                elif author.receive_update == 3:
                    logger.info("Sending notification via jabber to %s", author.jabber_contact)
                    template = read_template('/home/django/projects/fun/core/templates/core/post_jabber.txt', replace_newlines=False)
                    send_gearman_jabber(template.render(Context(context)), author.jabber_contact)

    cache.delete_pattern('template.cache.post.content*')

    def __str__(self):
        return "%s" % self.title

    def __unicode___(self):
        return "%s" % self.title

    def get_absolute_url(self):
        return "/post/" + str(self.id) + "/" + self.slug + "/"


class Rating(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(Author)
    post = models.ForeignKey(Post)
    rating = models.IntegerField()

    class Meta:
        unique_together = (('user', 'post'))

    def get_rating(self, post):
        return Rating.objects.filter(post__pk=post).aggregate(Avg('rating'))


class NewsLetter(models.Model):
    id = models.AutoField(primary_key=True)
    subject = models.CharField(max_length=150)
    content = models.TextField()
    date_created = models.DateTimeField(default=timezone.now)
    date_updated = models.DateTimeField(default=timezone.now)
    sent = models.BooleanField(default=False)
    date_sent = models.DateTimeField(blank=True, null=True)

    class Meta:
        ordering = ['-date_created']

    def __str__(self):
        return "%s" % self.subject

    def __unicode__(self):
        return "%s" % self.subject

post_save.connect(post_save_user, sender=Author)

core/templates/core/author_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block extra_css %}
<style>
    .avatar {
        width:128px;
        height:128px;
    }
</style>
{% endblock %}

{% block content %}
<div class="container-fluid col-md-12 col-md-offset-4">
    <div class="pull-left">
        <img class="img-rounded avatar" src="{{ STATIC_URL }}{{ author.avatar }}"/>
    </div>
    <div class="form-group">
        <label class="control-label">Име</label>
        <p>{{ author.first_name }} {{ author.last_name }}</p>
    </div>
</div>
{% endblock %}

core/templates/core/author_form.html
{% extends "base.html" %}
{% load i18n %}
{% load bootstrap3 %}

{% block content %}

<div class="col-md-offset-4 col-md-4">
<form action="{% url 'edit_profile' pk=user.pk %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">
            {% bootstrap_icon "ok" %} {% trans 'Submit' %}
        </button>
    {% endbuttons %}
</form>
</div>

{% endblock %}

core/templates/core/category_form.html
{% extends "base.html" %}
{% load i18n %}
{% load bootstrap3 %}

{% block content %}
<div class="col-md-offset-4 col-md-4">
<form action="" method="post">{% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">
            {% bootstrap_icon "ok" %} {% trans 'Submit' %}
        </button>
    {% endbuttons %}
</form>
</div>

{% endblock %}

core/templates/core/post_body.html
{% load cache %}
<div class="post">
    <ul>
        <div class="post-title"><h2><a href="{% url 'post' pk=post.pk slug=post.slug %}" rel="bookmark" itemprop="url"><span itemprop="headline">{{ post.title }}</span></a></h2></div>
        <ul>
            <div class="post-time" itemprop="datePublished">{{ post.date_created }} от <img class="img-rounded avatar" src="{{ STATIC_URL }}{{ post.author.avatar }}"/> <span itemprop="author">{{ post.author }}</span> </div>
            <div class="post-content" itemprop="text">
                {% if post.unsafe and not user.is_authenticated %}
                    <p>Съдържанието е маркирано като "unsafe". За да видите това трябва да се <a href="{% url 'registration_register' %}">регистрирате</a> или да <a href="{% url 'auth_login' %}">влезете в профила си</a>.</p>
                {% else %}
                    {% cache 600 post.content post.pk %}
                    {% autoescape off %}
                    {{ post.content | linebreaks | safe }}
                    {% endautoescape %}
                    {% endcache %}
                {% endif %}
            </div>
            <div class="post-content" itemscope itemtype="aggregateRating">
                Рейтинг: {% if post.rating_set.count > 0 %}<span itemprop="ratingValue">{{ post.rating_set.count }}</span>{% else %}<span itemprop="ratingValue">0</span>{% endif %}
                <a href="{% url 'rating_up' id=post.pk slug=post.slug %}">+</a>
                <a href="{% url 'rating_down' id=post.pk slug=post.slug %}">-</a>
            </div>
            {% if post.author == user %}
            <div class="post-content">
                <a href="{% url 'edit_post' pk=post.pk %}">Редактирай</a>
            </div>
            {% endif %}
        </ul>
    </ul>
</div>

core/templates/core/post_detail.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load i18n %}

{% block keywords %}
    <meta name="Keywords" content="{{ post.keywords }}"/>
{% endblock %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block mata_title %}
    {{ post.title }}
{% endblock %}

{% block extra_css %}
<style>
    .avatar {
        width:32px;
        height:32px;
    }
</style>
{% endblock %}

{% block content %}
    <div itemprop="blogPost" itemscope itemtype="https://schema.org/Blog">
        <div class="col-md-12">
            <ol class="breadcrumb" class="col-md-2">
                <li><a href="{% url 'index' %}">Начало</a></li>
                <li class="active"><a href="{% url 'post' pk=post.pk slug=post.slug %}">{{ post.title }}</a></li>
        </div>
        {% include "core/post_body.html" %}
    </div>
{% endblock %}

core/templates/core/post_form.html
{% extends "base.html" %}
{% load i18n %}
{% load bootstrap3 %}

{% block content %}

<div class="col-md-offset-4 col-md-4">
{% if user.first_name and user.last_name %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">
        {% bootstrap_icon "ok" button_type="button" %} {% trans 'Submit' %}
    </button>
    {% endbuttons %}
</form>
{% else %}
    <p> Моля редактирайте профила си <a href="{% url 'edit_profile' pk=user.pk %}">тук</a> преди да добавяте постове.
{% endif %}
</div>
{% endblock %}

core/templates/core/post_list.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load i18n %}
{% load cache %}

{% block extra_css %}
<style>
    .avatar {
        width:32px;
        height:32px;
    }
</style>
{% endblock %}

{% block content %}
{% if object_list %}
    {% for post in object_list %}
    <div itemprop="blogPost" itemscope itemtype="https://schema.org/Blog">
        <div class="col-md-offset-2">
            {% include "core/post_body.html" %}
        </div>
        <br />
    </div>
    {% endfor %}
    {% if is_paginated %}
        <div class="col-md-offset-6">
            {% bootstrap_pagination page_obj %}
        </div>
    {% endif %}

{% endif %}
{% endblock %}

core/templates/core/search_results.html
{% extends "base.html" %}

{% block content %}
{% for post in found_entries %}
        <div class="col-md-offset-2">
            <ul>
                <div class="post-title"><h2><a href="{% url 'post' pk=post.pk slug=post.slug %}">{{ post.title }}</a></h2></div>
                <ul>
                    <div class="post-time">{{ post.date_created }}</div>
                    <div class="post-content">
                        {% autoescape off %}
                        {{ post.content | linebreaks | safe }}
                        {% endautoescape %}
                    </div>
                </ul>
            </ul>
        </div>
    <br />
{% endfor %}
{% endblock %}